# SPDX-FileCopyrightText: 2026 Marcel Petrick <mail@marcelpetrick.it>
# SPDX-License-Identifier: GPL-3.0-or-later
"""Emit the KiCad project file, the fp-lib-table and the custom DRC rules.

The point of generating these rather than clicking them in: the thermal rule
that makes Variant B work is a *number* (0.15 mm), and a number that only lives
in a designer's memory gets widened the first time a route is awkward. Here it
is a DRC rule that fails the build.
"""
from __future__ import annotations

import json
from pathlib import Path

from .design import NETCLASSES
from .variants import Variant


def kicad_pro(v: Variant) -> str:
    classes = []
    patterns = []
    for name, nc in NETCLASSES.items():
        classes.append({
            "name": name,
            "clearance": nc["clearance"],
            "track_width": nc["track"],
            "via_diameter": nc["via"],
            "via_drill": nc["drill"],
            "microvia_diameter": 0.3,
            "microvia_drill": 0.1,
            "diff_pair_width": nc.get("diff_pair_width", 0.2),
            "diff_pair_gap": nc.get("diff_pair_gap", 0.25),
            "diff_pair_via_gap": 0.25,
            "bus_width": 12,
            "wire_width": 6,
            "line_style": 0,
            "pcb_color": "rgba(0, 0, 0, 0.000)",
            "schematic_color": "rgba(0, 0, 0, 0.000)",
        })
        for net in nc["nets"]:
            patterns.append({"netclass": name, "pattern": net})

    doc = {
        "board": {
            "design_settings": {
                "defaults": {
                    "board_outline_line_width": 0.1,
                    "copper_line_width": 0.2,
                    "copper_text_size_h": 1.0,
                    "copper_text_size_v": 1.0,
                    "copper_text_thickness": 0.15,
                    "silk_line_width": 0.12,
                    "silk_text_size_h": 0.8,
                    "silk_text_size_v": 0.8,
                    "silk_text_thickness": 0.13,
                },
                "rules": {
                    "min_clearance": 0.15,
                    "min_copper_edge_clearance": 0.3,
                    "min_hole_clearance": 0.25,
                    "min_hole_to_hole": 0.25,
                    "min_microvia_diameter": 0.2,
                    "min_microvia_drill": 0.1,
                    "min_silk_clearance": 0.0,
                    "min_text_height": 0.6,
                    "min_text_thickness": 0.08,
                    "min_through_hole_diameter": 0.3,
                    "min_track_width": 0.127,
                    "min_via_annular_width": 0.13,
                    "min_via_diameter": 0.45,
                },
                "track_widths": [0.0, 0.15, 0.25, 0.4, 0.5, 0.6],
                "via_dimensions": [
                    {"diameter": 0.0, "drill": 0.0},
                    {"diameter": 0.6, "drill": 0.3},
                    {"diameter": 0.8, "drill": 0.4},
                ],
            },
        },
        "meta": {"filename": f"env-sensor-{v.key}.kicad_pro", "version": 3},
        "net_settings": {
            "classes": classes,
            "meta": {"version": 4},
            "netclass_patterns": patterns,
        },
        "sheets": [],
        "text_variables": {
            "HW_REV": v.revision,
            "VARIANT": v.name,
        },
    }
    return json.dumps(doc, indent=2) + "\n"


FP_LIB_TABLE = """(fp_lib_table
  (version 7)
  (lib (name "sensorly")(type "KiCad")(uri "${KIPRJMOD}/../lib/sensorly.pretty")(options "")(descr "ENV sensor project footprints - vendored, see hardware/lib/README.md"))
)
"""


def dru(v: Variant) -> str:
    """Custom DRC rules. These encode docs/30-electrical-design-spec.md."""
    rules = ['(version 1)',
             '',
             '# Generated by tools/boardgen - edit the generator, not this file.',
             f'# Variant {v.key.upper()} ({v.name}), {v.revision}',
             '',
             '(rule "sensor island trace width"',
             '\t(constraint track_width (min 0.13mm) (max 0.15mm))',
             '\t(condition "A.NetClass == \'SensorIsland\'")',
             '\t# EDS S3.1: the four island traces conduct 5x more heat than the',
             '\t# whole FR-4 neck. Widening them is a thermal change, not a',
             '\t# routing convenience.',
             ')',
             '',
             '(rule "no vias on the sensor nets"',
             '\t(constraint disallow via)',
             '\t(condition "A.NetClass == \'SensorIsland\'")',
             '\t# EDS S3.1.2: no stitching or thermal vias anywhere on the island',
             '\t# path - a via is a copper column straight through the board.',
             ')',
             '',
             '(rule "power track width"',
             '\t(constraint track_width (min 0.4mm))',
             '\t(condition "A.NetClass == \'Power\' && A.Type == \'Track\'")',
             ')',
             '',
             '(rule "USB differential pair"',
             '\t(constraint diff_pair_gap (min 0.15mm) (opt 0.2mm))',
             '\t(constraint diff_pair_uncoupled (max 2mm))',
             '\t(condition "A.NetClass == \'USB\'")',
             ')',
             '',
             '(rule "copper to board edge"',
             '\t(constraint edge_clearance (min 0.3mm))',
             ')',
             '',
             '(rule "JLCPCB-class minimum trace"',
             '\t(constraint track_width (min 0.127mm))',
             '\t# P-04: nothing that needs an advanced process.',
             ')',
             '',
             '(rule "JLCPCB-class minimum drill"',
             '\t(constraint hole_size (min 0.2mm))',
             ')',
             '']
    if v.key == "b":
        rules += [
            '(rule "nothing but the sensor nets crosses the neck"',
            '\t(constraint disallow track via pad zone)',
            '\t(condition "A.NetClass != \'SensorIsland\' && A.NetClass != \'Power\' '
            '&& A.insideArea(\'Thermal isolation - no inner copper\')")',
            '\t# EDS S3.1.1: exactly four nets reach the sensor. This rule is the',
            '\t# machine-readable form of that sentence.',
            ')',
            '',
        ]
    return "\n".join(rules)


def write_all(root: Path, v: Variant):
    d = root / "hardware" / f"variant-{v.key}"
    d.mkdir(parents=True, exist_ok=True)
    (d / f"env-sensor-{v.key}.kicad_pro").write_text(kicad_pro(v))
    (d / f"env-sensor-{v.key}.kicad_dru").write_text(dru(v))
    (d / "fp-lib-table").write_text(FP_LIB_TABLE)
