// SPDX-FileCopyrightText: 2026 Marcel Petrick <mail@marcelpetrick.it>
// SPDX-License-Identifier: GPL-3.0-or-later
// Generated by tools/boardgen/enclosure.py for variant A (Compact). Do not edit.
variant = "a";
board_w = 30.0; board_h = 34.0; board_t = 1.6;
wall = 2.0; floor_t = 2.0; lid_t = 2.0;
clear_xy = 0.6; fillet = 1.5; tol = 0.35;
rib_w = 1.6;
inner_w = 37.0; inner_h = 35.2; inner_z = 15.7;
board_z = 6.0; top_clear = 8.1;
outer_w = 41.0; outer_h = 39.2; outer_z = 19.7;
batt = [35.0, 30.0, 5.0];
// battery bay in BOARD coordinates; it may extend past the
// board edge, because the cavity is sized to the cell, not the PCB
batt_bay = [-2.5, 6.9, 32.5, 28.299999999999997];
divider_y = -1;
neck_slot = [0, 0];
antenna_keepout = [0.0, 0.0, 30.0, 5.9];
// [x, y, w, h] on the board, in board coordinates
vents = [[12.0, 30.299999999999997, 8.0, 1.2]];
vent_wall = "bottom";
// [centre, width, height] on the sensor-chamber wall
side_vents = [[10.6, 1.2, 3.0], [13.2, 1.2, 3.0], [15.799999999999999, 1.2, 3.0], [18.4, 1.2, 3.0]];
// [x, y, diameter] hold-down pillars, board coordinates
holddowns = [[1.6, 15.6, 2.2], [12.6, 31.9, 2.2], [1.6, 32.4, 1.8]];
// [wall, x, y, width, height, z] - x,y in board coordinates
cutouts = [["left", 5.5, 24.5, 9.549999999999999, 3.5100000000000002, 0.0], ["right", 22.85, 24.5, 6.35, 4.0, 1.0], ["lid", 13.7, 28.0, 4.0, 4.0, 0.0], ["lid", 11.3, 22.0, 2.0, 2.0, 0.0]];
board_outline = [[0, 0], [30.0, 0], [30.0, 34.0], [0, 34.0]];
