# SPDX-FileCopyrightText: 2026 Marcel Petrick <mail@marcelpetrick.it>
# SPDX-License-Identifier: GPL-3.0-or-later
"""Write docs/45-thermal-model.md from the live board geometry."""
from pathlib import Path

from .boardgen.thermal import report

HEAD = """# 45 — Thermal Screening Model (generated)

<!-- Generated by `make thermal` from tools/boardgen/thermal.py. Do not edit:
     change the model, re-run, commit both. -->

Purpose: compare idealized conduction paths and expose assumptions. Neck
dimensions come from the generated model, but the A-sized solid copper slab
does not represent A's actual copper-free sensor zone. This calculation cannot
rank the finished instruments or predict their temperature errors.

k(FR-4) = 0.30 W/m·K · k(Cu) = 385 W/m·K · 35 µm copper · 1.6 mm FR-4

"""

if __name__ == "__main__":
    out = Path(__file__).resolve().parents[1] / "docs" / "45-thermal-model.md"
    out.write_text(HEAD + report() + "\n")
