# SPDX-FileCopyrightText: 2026 Marcel Petrick <mail@marcelpetrick.it>
# SPDX-License-Identifier: GPL-3.0-or-later
"""Write docs/45-thermal-model.md from the live board geometry."""
from pathlib import Path

from .boardgen.thermal import report

HEAD = """# 45 — Thermal Screening Model (generated)

<!-- Generated by `make thermal` from tools/boardgen/thermal.py. Do not edit:
     change the model, re-run, commit both. -->

Purpose: rank the two floorplans and find the dominant term, before any
hardware exists. Inputs are the *actual* generated geometry — neck size, trace
width, sensor-to-charger distance — read straight from the board model, so this
file cannot drift away from the boards.

k(FR-4) = 0.30 W/m·K · k(Cu) = 385 W/m·K · 35 µm copper · 1.6 mm FR-4

"""

if __name__ == "__main__":
    out = Path(__file__).resolve().parents[1] / "docs" / "45-thermal-model.md"
    out.write_text(HEAD + report() + "\n")
